import { GB, US, DE, FR, IT, ES, JP, CN, RU, IN, BR, CA, AU, KR, MX, ID, NL, SA, CH, TR } from 'country-flag-icons/react/3x2';

interface Country {
  id: string;
  name: string;
  code: string;
}

const turkiye = { id: "2", name: "Türkiye", code: "TR" };

export const countries: Country[] = [
  turkiye,
  ...[
    { id: "33", name: "Abd", code: "US" },
    { id: "166", name: "Afganistan", code: "AF" },
    { id: "13", name: "Almanya", code: "DE" },
    { id: "17", name: "Andorra", code: "AD" },
    { id: "140", name: "Angola", code: "AO" },
    { id: "125", name: "Anguilla", code: "AI" },
    { id: "90", name: "Antigua ve Barbuda", code: "AG" },
    { id: "199", name: "Arjantin", code: "AR" },
    { id: "25", name: "Arnavutluk", code: "AL" },
    { id: "153", name: "Aruba", code: "AW" },
    { id: "213", name: "Ascension", code: "AC" },
    { id: "1216", name: "Atlantik Okyanusu", code: "XA" },
    { id: "59", name: "Avustralya", code: "AU" },
    { id: "35", name: "Avusturya", code: "AT" },
    { id: "5", name: "Azerbaycan", code: "AZ" },
    { id: "54", name: "Bahamalar", code: "BS" },
    { id: "132", name: "Bahreyn", code: "BH" },
    { id: "177", name: "Banglades", code: "BD" },
    { id: "188", name: "Barbados", code: "BB" },
    { id: "208", name: "Belarus", code: "BY" },
    { id: "11", name: "Belcika", code: "BE" },
    { id: "182", name: "Belize", code: "BZ" },
    { id: "181", name: "Benin", code: "BJ" },
    { id: "51", name: "Bermuda", code: "BM" },
    { id: "93", name: "Birlesik Arap Emirligi", code: "AE" },
    { id: "83", name: "Bolivya", code: "BO" },
    { id: "9", name: "Bosna Hersek", code: "BA" },
    { id: "167", name: "Botsvana", code: "BW" },
    { id: "146", name: "Brezilya", code: "BR" },
    { id: "97", name: "Brunei", code: "BN" },
    { id: "44", name: "Bulgaristan", code: "BG" },
    { id: "91", name: "Burkina Faso", code: "BF" },
    { id: "65", name: "Burundi", code: "BI" },
    { id: "155", name: "Butan", code: "BT" },
    { id: "156", name: "Cad", code: "TD" },
    { id: "43", name: "Cecenistan", code: "CE" },
    { id: "16", name: "Cek Cumhuriyeti", code: "CZ" },
    { id: "86", name: "Cezayir", code: "DZ" },
    { id: "160", name: "Cibuti", code: "DJ" },
    { id: "61", name: "Cin", code: "CN" },
    { id: "26", name: "Danimarka", code: "DK" },
    { id: "180", name: "Demokratik Kongo Cumhuriyeti", code: "CD" },
    { id: "176", name: "Dogu Timor", code: "TL" },
    { id: "123", name: "Dominik", code: "DM" },
    { id: "72", name: "Dominik Cumhuriyeti", code: "DO" },
    { id: "139", name: "Ekvator", code: "EC" },
    { id: "63", name: "Ekvator Ginesi", code: "GQ" },
    { id: "165", name: "El Salvador", code: "SV" },
    { id: "117", name: "Endonezya", code: "ID" },
    { id: "175", name: "Eritre", code: "ER" },
    { id: "104", name: "Ermenistan", code: "AM" },
    { id: "6", name: "Estonya", code: "EE" },
    { id: "170", name: "Eswatini", code: "SZ" },
    { id: "95", name: "Etyopya", code: "ET" },
    { id: "145", name: "Fas", code: "MA" },
    { id: "197", name: "Fiji", code: "FJ" },
    { id: "120", name: "Fildisi Sahili", code: "CI" },
    { id: "126", name: "Filipinler", code: "PH" },
    { id: "204", name: "Filistin", code: "PS" },
    { id: "41", name: "Finlandiya", code: "FI" },
    { id: "21", name: "Fransa", code: "FR" },
    { id: "79", name: "Gabon", code: "GA" },
    { id: "109", name: "Gambiya", code: "GM" },
    { id: "143", name: "Gana", code: "GH" },
    { id: "111", name: "Gine", code: "GN" },
    { id: "58", name: "Grenada", code: "GD" },
    { id: "48", name: "Gronland", code: "GL" },
    { id: "171", name: "Guadelope", code: "GP" },
    { id: "169", name: "Guam Adasi", code: "GU" },
    { id: "99", name: "Guatemala", code: "GT" },
    { id: "67", name: "Guney Afrika", code: "ZA" },
    { id: "128", name: "Guney Kore", code: "KR" },
    { id: "214", name: "Guney Sudan", code: "SS" },
    { id: "62", name: "Gurcistan", code: "GE" },
    { id: "82", name: "Guyana", code: "GY" },
    { id: "70", name: "Haiti", code: "HT" },
    { id: "187", name: "Hindistan", code: "IN" },
    { id: "30", name: "Hirvatistan", code: "HR" },
    { id: "4", name: "Hollanda", code: "NL" },
    { id: "66", name: "Hollanda Antilleri", code: "AN" },
    { id: "105", name: "Honduras", code: "HN" },
    { id: "113", name: "Hong Kong", code: "HK" },
    { id: "15", name: "Ingiltere", code: "GB" },
    { id: "124", name: "Irak", code: "IQ" },
    { id: "202", name: "Iran", code: "IR" },
    { id: "32", name: "Irlanda", code: "IE" },
    { id: "23", name: "Ispanya", code: "ES" },
    { id: "205", name: "Israil", code: "IL" },
    { id: "12", name: "Isvec", code: "SE" },
    { id: "49", name: "Isvicre", code: "CH" },
    { id: "8", name: "Italya", code: "IT" },
    { id: "122", name: "Izlanda", code: "IS" },
    { id: "119", name: "Jamaika", code: "JM" },
    { id: "116", name: "Japonya", code: "JP" },
    { id: "161", name: "Kambocya", code: "KH" },
    { id: "184", name: "Kamerun", code: "CM" },
    { id: "52", name: "Kanada", code: "CA" },
    { id: "34", name: "Karadag", code: "ME" },
    { id: "94", name: "Katar", code: "QA" },
    { id: "92", name: "Kazakistan", code: "KZ" },
    { id: "114", name: "Kenya", code: "KE" },
    { id: "168", name: "Kirgizistan", code: "KG" },
    { id: "57", name: "Kolombiya", code: "CO" },
    { id: "88", name: "Komorlar", code: "KM" },
    { id: "18", name: "Kosova", code: "XK" },
    { id: "162", name: "Kostarika", code: "CR" },
    { id: "209", name: "Kuba", code: "CU" },
    { id: "206", name: "Kudus", code: "PS" },
    { id: "133", name: "Kuveyt", code: "KW" },
    { id: "1", name: "Kuzey Kibris", code: "CY" },
    { id: "142", name: "Kuzey Kore", code: "KP" },
    { id: "134", name: "Laos", code: "LA" },
    { id: "174", name: "Lesoto", code: "LS" },
    { id: "20", name: "Letonya", code: "LV" },
    { id: "73", name: "Liberya", code: "LR" },
    { id: "203", name: "Libya", code: "LY" },
    { id: "38", name: "Liechtenstein", code: "LI" },
    { id: "47", name: "Litvanya", code: "LT" },
    { id: "42", name: "Lubnan", code: "LB" },
    { id: "31", name: "Luksemburg", code: "LU" },
    { id: "7", name: "Macaristan", code: "HU" },
    { id: "98", name: "Madagaskar", code: "MG" },
    { id: "100", name: "Makao", code: "MO" },
    { id: "28", name: "Makedonya", code: "MK" },
    { id: "55", name: "Malavi", code: "MW" },
    { id: "103", name: "Maldivler", code: "MV" },
    { id: "107", name: "Malezya", code: "MY" },
    { id: "152", name: "Mali", code: "ML" },
    { id: "24", name: "Malta", code: "MT" },
    { id: "212", name: "Man Adasi", code: "IM" },
    { id: "87", name: "Martinik", code: "MQ" },
    { id: "164", name: "Mauritius Adasi", code: "MU" },
    { id: "157", name: "Mayotte", code: "YT" },
    { id: "53", name: "Meksika", code: "MX" },
    { id: "85", name: "Mikronezya", code: "FM" },
    { id: "189", name: "Misir", code: "EG" },
    { id: "60", name: "Mogolistan", code: "MN" },
    { id: "46", name: "Moldavya", code: "MD" },
    { id: "3", name: "Monako", code: "MC" },
    { id: "147", name: "Montserrat", code: "MS" },
    { id: "106", name: "Moritanya", code: "MR" },
    { id: "151", name: "Mozambik", code: "MZ" },
    { id: "154", name: "Myanmar", code: "MM" },
    { id: "196", name: "Namibya", code: "NA" },
    { id: "76", name: "Nepal", code: "NP" },
    { id: "84", name: "Nijer", code: "NE" },
    { id: "127", name: "Nijerya", code: "NG" },
    { id: "141", name: "Nikaragua", code: "NI" },
    { id: "178", name: "Niue", code: "NU" },
    { id: "36", name: "Norvec", code: "NO" },
    { id: "80", name: "Orta Afrika Cumhuriyeti", code: "CF" },
    { id: "131", name: "Ozbekistan", code: "UZ" },
    { id: "77", name: "Pakistan", code: "PK" },
    { id: "149", name: "Palau", code: "PW" },
    { id: "89", name: "Panama", code: "PA" },
    { id: "185", name: "Papua Yeni Gine", code: "PG" },
    { id: "194", name: "Paraguay", code: "PY" },
    { id: "69", name: "Peru", code: "PE" },
    { id: "183", name: "Pitcairn Adasi", code: "PN" },
    { id: "39", name: "Polonya", code: "PL" },
    { id: "45", name: "Portekiz", code: "PT" },
    { id: "68", name: "Porto Riko", code: "PR" },
    { id: "112", name: "Reunion", code: "RE" },
    { id: "37", name: "Romanya", code: "RO" },
    { id: "81", name: "Ruanda", code: "RW" },
    { id: "207", name: "Rusya", code: "RU" },
    { id: "64", name: "Suudi Arabistan", code: "SA" },
    { id: "198", name: "Samoa", code: "WS" },
    { id: "102", name: "Senegal", code: "SN" },
    { id: "138", name: "Seysel Adalari", code: "SC" },
    { id: "210", name: "Sierra Leone", code: "SL" },
    { id: "200", name: "Sili", code: "CL" },
    { id: "179", name: "Singapur", code: "SG" },
    { id: "27", name: "Sirbistan", code: "RS" },
    { id: "14", name: "Slovakya", code: "SK" },
    { id: "19", name: "Slovenya", code: "SI" },
    { id: "150", name: "Somali", code: "SO" },
    { id: "74", name: "Sri Lanka", code: "LK" },
    { id: "136", name: "St. Lucia", code: "LC" },
    { id: "129", name: "Sudan", code: "SD" },
    { id: "172", name: "Surinam", code: "SR" },
    { id: "191", name: "Suriye", code: "SY" },
    { id: "163", name: "Svalbard", code: "SJ" },
    { id: "101", name: "Tacikistan", code: "TJ" },
    { id: "110", name: "Tanzanya", code: "TZ" },
    { id: "137", name: "Tayland", code: "TH" },
    { id: "108", name: "Tayvan", code: "TW" },
    { id: "71", name: "Togo", code: "TG" },
    { id: "130", name: "Tonga", code: "TO" },
    { id: "96", name: "Trinidad ve Tobago", code: "TT" },
    { id: "118", name: "Tunus", code: "TN" },
    { id: "159", name: "Turkmenistan", code: "TM" },
    { id: "75", name: "Uganda", code: "UG" },
    { id: "40", name: "Ukrayna", code: "UA" },
    { id: "29", name: "Ukrayna-Kirim", code: "UA" },
    { id: "173", name: "Umman", code: "OM" },
    { id: "192", name: "Urdun", code: "JO" },
    { id: "201", name: "Uruguay", code: "UY" },
    { id: "56", name: "Vanuatu", code: "VU" },
    { id: "10", name: "Vatikan", code: "VA" },
    { id: "186", name: "Venezuela", code: "VE" },
    { id: "135", name: "Vietnam", code: "VN" },
    { id: "148", name: "Yemen", code: "YE" },
    { id: "115", name: "Yeni Kaledonya", code: "NC" },
    { id: "193", name: "Yeni Zelanda", code: "NZ" },
    { id: "144", name: "Yesil Burun", code: "CV" },
    { id: "22", name: "Yunanistan", code: "GR" },
    { id: "158", name: "Zambiya", code: "ZM" },
    { id: "216", name: "Zimbabve", code: "ZW" }
  ].sort((a, b) => a.name.localeCompare(b.name))
];